# Generated by Django 2.0.7 on 2021-09-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_dope',
        ),
    ]
