# Generated by Django 2.0.7 on 2021-09-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0002_delete_home_dope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Forms',
            new_name='Contact_Formss',
        ),
    ]
