# Generated by Django 2.0.7 on 2021-09-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0003_auto_20210929_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Formss',
            new_name='Contact_Forms',
        ),
    ]
