# Generated by Django 2.0.7 on 2021-09-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0004_auto_20210929_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Forms',
        ),
        migrations.DeleteModel(
            name='login_Detials',
        ),
        migrations.DeleteModel(
            name='Register_Account',
        ),
    ]
