# Generated by Django 2.0.7 on 2021-09-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0006_contact_forms_login_detials_register_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_Account',
        ),
    ]
