# Generated by Django 2.0.7 on 2021-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0007_delete_register_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
