# Generated by Django 2.0.7 on 2021-09-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='secondContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CUstomer',
        ),
    ]
