# Generated by Django 2.0.7 on 2021-09-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0010_auto_20210930_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='secondContactForm',
        ),
        migrations.RenameField(
            model_name='contact_forms',
            old_name='Address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact_forms',
            old_name='Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact_forms',
            old_name='emailaddress',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact_forms',
            old_name='PhoneNumber',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact_forms',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_forms',
            name='message',
            field=models.CharField(max_length=800),
        ),
    ]
