# Generated by Django 2.0.7 on 2021-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0011_auto_20210930_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_forms',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
