# Generated by Django 2.0.7 on 2021-09-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juliusgroups', '0012_auto_20210930_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_forms',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact_forms',
            name='message',
            field=models.TextField(),
        ),
    ]
